version: 1
# python run-loop.py .\examples\config-windows.yaml
host: http://localhost:7860
path: ./prompts/
schedule:
  time 7:00 - 23:00
#  start: 7
#  stop: 23
# log setter
log:
  # log output filename
  # *** CHANGE FROM FOLDER TO FILENAME *** 
  path: f:/ai/logs/run.log
  # remain days / logrotater has no rotate bug
  days: 7
  # logging level
  level: info
  # print stdin list
  # info information = default
  # verbose verbose information
  # debug debug information
  # error exceptions
  # warning/ critical not implemented
  print_levels: ['info', 'verbose', 'warning', 'error', 'critical']
# clone is model clone from NAS
clone:
  clone: true
  src: f:/ai/models/
  dest: e:/ai/models/
  folders:
    - Stable-Diffusion
    - vae
    - Lora
    - embbeded

loop:
  mode: true # custom loop mode false = sequential loop
  loop_count: 1 # 0 is infinite
  commands:
    - clone
    - check
  #  - ping
  #  - txt2img
  #  - img2img
  #  - img2txt2img take
  #  - img2txt2img retake
    - custom subprocess cmd /c dir
    - custom ls .
  #  - custom 1
    - sleep 5

txt2img:
  # model,vae file,mode
  # models: ./sample/models.csv # from csv file
  - "sd_xl_base_1.0",Automatic,XL
  - "AnythingV5Ink_v32Ink",orangemix-vae.safetensors,SFW
  - "sd_xl_base_0.9",Automatic,SKIP
  # Modes are setting task running genres, see abort_matrix
  # XL -> only xl
  # SFW -> only sfw
  # SKIP -> task skip
  # prompt,folder,number,genre,filename pattern
  # prompts: ./prompts/prompts.csv  # from csv file 
  - fantasy,fantasy,10,sfw,[num]-[seed]-Fantasy
  - xl-fantasy,fantasy,10,xl,[num]-[seed]-Fantasy
  - car,car,4,sfw,[num]-[seed]-Car
  # with prefix
  # ./prompt/prompt-girls-fantasy.yaml    number 10 output f:/ai/outputs/fantasy-images/000000-000000-Fantasy.png
  # ./prompt/prompt-girls-xl-fantasy.yaml number 10 output f:/ai/outputs/fantasy-images/000000-000000-Fantasy.png
  # ./prompt/prompt-car.yaml number 5 output f:/ai/outputs/car-images/000000-000000-Car.png
  prefix:
    default: 'prompt-girls'
    exception: 'prompt-'
    exception_list: ['monster', 'landscape', 'animal', 'car', 'building', 'weapon', 'robot']
    # exception_list: ./prompts/exceptions.csv
    suffix: '.yaml'
  prompt_base: ./prompts/
  output: f:/ai/outputs/
  folder_suffix: '-images'
  # output folder ex.) f:\ai\outputs\monster-images\000001-999999-Orc.png
  #overrides: #set option overrides
  # abort_matrix is MODE: GENRE list
  abort_matrix: # '*' is all genres
    BOTH: ['sfw', 'nsfw']
    SFW: ['sfw']
    NSFW: ['nsfw']
    XL: ['xl']
  coef_matrix:
    XL: 0.5
  # coef_matrix is coef for number, if number is 10, 10 * 0.5 = 5

# png only, yet
img2img:
  steps: 20
  denosing_stringth: 0.7
  n_iter: 2
  batch_size: 1
  file_pattern: 'img[num]-[seed]'
  dir:
    # seek input files from this folder's subfolders
    input: f:/ai/outputs/$retake/batch
    # ex. search
    # f:\ai\outputs\$retake/batch\cars\
    # f:\ai\outputs\$retake/batch\monster\
    # work folder
    work: f:/ai/outputs/$retake/.work
    # img2img image modified folder
    append: f:/ai/outputs/$retake/modified
    # img2img image mask folder
    mask: f:/ai/outputs/$retake/mask
    # complete img2img images folder
    ended: f:/ai/outputs/$retake/$end
    output: f:/ai/outputs/
    folder_suffix: -images
    # output images f:\ai\outputs\monster-images\img000001-9999999.png

# txt2img prompts from image infomations
img2txt2img:
  modelfile: prompt/model.csv # csv file get from model name to vae file
  # dry_run: true # dry run mode
  take:
    input: f:/ai/inputs/$retake/take  # input folder for images array str or str
    output: f:/ai/outputs/take2-images # output folder
    backup: f:/ai/outputs/$retake/take_bak # backup folder from input folder
    overrides:
      batch_size: 1
      n_iter: 1
      enable_hr: true # enable hr mode
      hr_scale: 2.25  # hr scale
      hr_upscaler: R-ESRGAN 4x+ Anime6B # hr upscaler
      denoise_strength: 0.5 # denoise strength
      hr_second_pass_steps: 5 # hr second pass steps
  retake:
    input: f:/ai/inputs/$retake/retake
    output: f:/ai/outputs/retake-images
    backup: f:/ai/outputs/$retake/retake_bak
    seed_diff: 1  # seed + 1
    overrides:
      # output images = batch_size * n_iter
      batch_size: 3 # same running stable diffusion batch size, dependenced GPU power, VRAM, model size and picture size
      n_iter: 2 # n times run stable diffusion
      enable_hr: false


custom:
    subprocess: cmd
    ls: ls