version: 2
options:
    output: ./outputs/examples-kenzen.txt
#    json: true # output JSON
    number: 10
methods:
    - random: 0 
    - cleanup: prompt negative_prompt
variables:
    negative: examples/V1/appends/000-negative.txt
    eyes: ['${eyeshape} ${eyeoddities} ${eyecolor}${eyemotion}']
    eyecolor: examples/V1/appends/e01-eyescolor.txt
    eyeshape: examples/V1/appends/e02-eyeshapes.txt
    eyeoddities: examples/V1/appends/e03-eyeoddities.txt
    eyemotion: examples/V1/appends/e04-eyemotion.txt
    hair: ['${haircolor} ${hairvariation} ${hairtop} ${hairside} ${hairback} ${hairbang} ${hairlength}']
    haircolor: examples/V1/appends/h01-haircolor.txt
    hairvariation: examples/V1/appends/h07-hairvariation.txt
    hairtop: examples/V1/appends/h06-hairtop.txt
    hairside: examples/V1/appends/h04-hairside.txt
    hairback: examples/V1/appends/h05-hairback.txt
    hairbang: examples/V1/appends/h03-hairbangs.txt
    hairlength: examples/V1/appends/h02-hairlength.txt
    clothes: ['${motif} ${clothes1} ${hair_ornament}','${clothes1}']
    hair_ornament: examples/V1/appends/h08-hair-ornament.txt
    hair_ornament_color: examples/V1/appends/s05-colors.txt
    hair_ornnament_motif: examples/V1/appends/c09-motif.txt
    motif: examples/V1/appends/c09-clothes-motif.txt
    clothes1: examples/V1/appends/c00-clothes.txt
    onepiece: examples/V1/appends/c01-onepiece.txt
    setclothes: examples/V1/appends/c01-setclothes-open.txt examples/V1/appends/c01-setclothes-close.txt examples/V1/appends/c01-setclothes-lora.txt
    cosplay: examples/V1/appends/c01-costume.txt
    swimware: examples/V1/appends/c01-swimwear.txt
    twopiece: examples/V1/appends/c01-twopiece.txt
    tops: examples/V1/appends/c02-tops.txt
    bottoms: ['${skirt}','${pant}']
    skirt: examples/V1/appends/c04-skirt.txt
    pant: examples/V1/appends/c04-pant.txt
    topsmotif: examples/V1/appends/c09-clothes-motif.txt
    topscolor: examples/V1/appends/c03-topscolors.txt
    bottomscolor: examples/V1/appends/c05-bottomscolors.txt
    panty: examples/V1/appends/c06-panties.txt
    pantymotif: examples/V1/appends/c09-motif.txt
    pantycolor: examples/V1/appends/c05-bottomscolors.txt
    bra: examples/V1/appends/c07-bra.txt
    bramotif: examples/V1/appends/c09-motif.txt
    bracolor: examples/V1/appends/c03-topscolors.txt
    overware: examples/V1/appends/c08-overware.txt
    overwarecolor: examples/V1/appends/c03-topscolors.txt

    doing: examples/V1/appends/d01-doings.txt
    motion: examples/V1/appends/d03-motions.txt

    lookings: examples/V1/appends/s00-lookings.txt
    coutenance: examples/V1/appends/s01-countenance.txt
    breast: examples/V1/appends/s02-breast.txt
    skin: examples/V1/appends/s03-skin.txt
    accessories: ['${hat}${head_accessory}${neck_accessory}${body_accessory}${hand_accessory}${leg_accessory}${accessory}']
    hand_accessory: examples/V1/appends/s04-hand-accessory.txt
    hand_accessory_motif: examples/V1/appends/c09-motif.txt
    hand_accessory_color: examples/V1/appends/s05-colors.txt
    neck_accessory: examples/V1/appends/s04-neck-accessory.txt
    neck_accessory_motif: examples/V1/appends/c09-motif.txt
    neck_accessory_color: examples/V1/appends/s05-colors.txt
    head_accessory: examples/V1/appends/s04-head-accessory.txt
    head_accessory_motif: examples/V1/appends/c09-motif.txt
    head_accessory_color: examples/V1/appends/s05-colors.txt
    body_accessory: examples/V1/appends/s04-body-accessory.txt
    body_accessory_motif: examples/V1/appends/c09-motif.txt
    body_accessory_color: examples/V1/appends/s05-colors.txt
    leg_accessory: examples/V1/appends/s04-leg-accessory.txt
    leg_motif: examples/V1/appends/c09-motif.txt
    leg_color: examples/V1/appends/s05-colors.txt
    accessory: examples/V1/appends/s04-accessories.txt
    accessory_motif: examples/V1/appends/c09-motif.txt
    accessory_color: examples/V1/appends/s05-colors.txt
    hat:  examples/V1/appends/s04-hat.txt
    hat_motif: examples/V1/appends/c09-motif.txt
    hat_color: examples/V1/appends/s05-colors.txt

    place: examples/V1/appends/p01-places.txt
    date: examples/V1/appends/p02-date.txt
    umbrella_motif: examples/V1/appends/c09-motif.txt
    umbrella_color: examples/V1/appends/s05-colors.txt 

    artstyle: ['${creation} (${artstyle1},${artstyle2})']
    artstyle1: examples/V1/appends/a01-artstyle.txt
    artstyle2: examples/V1/appends/a01-artstyle.txt
    creation: examples/V1/appends/a02-creation2.txt
    camera: ['${filter}${effect}${angle}${shot}${direction}']

    filter: examples/V1/appends/a03-filter.txt
    effect: examples/V1/appends/a04-effect.txt
    angle: examples/V1/appends/a05-angle.txt
    shot: examples/V1/appends/a06-shot.txt
    direction: examples/V1/appends/a07-direction.txt
    
command:
    prompt: "(${lookings}) wearing (${clothes}) ${accessories}, ${eyes} eyes, ${coutenance}, ${hair} hair, (${breast}) ${doing[1]}, ${artstyle}, ${place} ${motion}${camera}"
    negative_prompt: "nsfw,${negative}"
    seed: -1
    width: 512
    height: 704
    steps: 30
    cfg_scale: 12.5
    sampler_name: DPM++ SDE # not accept DPM++ SDE Karras
    batch_size: 1  # if you can use n size batch
    n_iter: 1 # also same butch count
